# -- Convienient Helpers --

# Print compile options of a target.
function(inspect_target target)
  if(NOT TARGET ${target})
    message(STATUS "inspect_target: ${target} does not exist")
    return()
  endif()
  section("Inspect: ${target}")
  get_target_property(_opts ${target} COMPILE_OPTIONS)
  get_target_property(_iopts ${target} INTERFACE_COMPILE_OPTIONS)
  get_target_property(_flags ${target} COMPILE_FLAGS)
  message(STATUS "  COMPILE_OPTIONS           : ${_opts}")
  message(STATUS "  INTERFACE_COMPILE_OPTIONS  : ${_iopts}")
  message(STATUS "  COMPILE_FLAGS              : ${_flags}")
endfunction()

# Check that a submodule directory is non-empty, otherwise fail with msg
macro(require_initialized_submodule DIR)
  file(GLOB _DIR_FILES "${DIR}/*")
  list(LENGTH _DIR_FILES _DIR_CONTENTS_LEN)
  if(_DIR_CONTENTS_LEN EQUAL 0)
    message(FATAL_ERROR "Missing dependency: ${DIR} is empty.\n" "Initialize the git submodule with:\n"
                        "    git -C ${DIR} submodule update --init .\n")
  endif()
endmacro()

# Single clean block printed at end of configure.
macro(print_config_summary)
  message(STATUS "")
  section("${PROJECT_NAME} v${PROJECT_VERSION}")
  message(STATUS "")
  message(STATUS "Module options:")
  message(STATUS "  BUILD_MODULE   : ${BUILD_MODULE}")
  message(STATUS "  BUILD_EXAMPLES : ${BUILD_EXAMPLES}")
  message(STATUS "  BUILD_TESTS    : ${BUILD_TESTS}")
  message(STATUS "  ENABLE_UBSAN   : ${ENABLE_UBSAN}")
  message(STATUS "  ENABLE_ASAN    : ${ENABLE_ASAN}")
  message(STATUS "  ENABLE_WERROR  : ${ENABLE_WERROR}")
  message(STATUS "")
  message(STATUS "Build options:")
  message(STATUS "  Build       : ${CMAKE_BUILD_TYPE}")
  message(STATUS "  Compiler    : ${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION}")
  message(STATUS "  Platform    : ${CMAKE_SYSTEM_NAME} (${CMAKE_SYSTEM_PROCESSOR})")
  message(STATUS "")
  message(STATUS "Dependencies:")
  message(STATUS "  OpenSSL     : ${OPENSSL_VERSION} (${OPENSSL_INCLUDE_DIR})")
  message(STATUS "  httpd       : ${HTTPD_VERSION} (${HTTPD_INCLUDE_DIR})")
  message(STATUS "  APR         : ${APR_VERSION} (${APR_INCLUDE_DIR})")
  message(STATUS "  APU         : ${APU_VERSION} (${APU_INCLUDE_DIR})")
  message(STATUS "")
endmacro()
