# -- CPack packaging --

set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_VERSION_MAJOR "${PROJECT_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "HTTP/3 module for Apache httpd")
set(CPACK_PACKAGE_VENDOR "machine-moon")
set(CPACK_PACKAGE_CONTACT "https://github.com/machine-moon/mod_http3/issues")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/machine-moon/mod_http3")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
set(FILE_NAME "${PROJECT_NAME}-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")

# Catch non-release builds by appending the build type to the file name
if(NOT CMAKE_BUILD_TYPE STREQUAL "Release")
    set(FILE_NAME "${CMAKE_BUILD_TYPE}-${CPACK_PACKAGE_FILE_NAME}")
endif()

string(TOLOWER "${FILE_NAME}" CPACK_PACKAGE_FILE_NAME)
set(CPACK_PACKAGE_CHECKSUM "SHA512")
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_BINARY_DIR}/dist")
set(CPACK_GENERATOR "ZIP;TGZ")

include(CPack)
